Properly handle HTML within component tags
AllianceSoftware/alliance-platform-py pull request #14
Opened 2024-05-09 06:10 UTC by davecoates

The main commit for HTML support is 60cd91f, however the commits prior refactored some code to make the changes easier to implement & test.

Specifically, with codegen we can now define JSX directly and then have the printer either output it as JSX (good for testing, debugging), or as `createElement` calls used in the browser.

Commit by commit review is recommended.

2024-05-11 08:17 UTC, micahklaz requested changes
Some comments to check

2024-05-12 23:56 UTC, davecoates commented on packages/ap-frontend/alliance_platform/frontend/templatetags/react.py
> +                    StringLiteral(key) if "-" in key else Identifier(underscore_to_camel(key)),
Only other attributes are dashes, but html attributes are case insensitive so there's no danger in lowercasing - i've added this now

2024-05-12 23:56 UTC, davecoates commented on packages/ap-frontend/alliance_platform/frontend/templatetags/react.py
> +from ...codegen.typescript import UnconvertibleValueException
ah thanks, need to work out better pycharm setup for the monorepo

2024-05-12 23:56 UTC, davecoates commented on packages/ap-codegen/tests/test_printer.py
> +
Good idea, done

2024-05-12 23:57 UTC, davecoates commented on packages/ap-codegen/alliance_platform/codegen/printer.py
> +            if node.leading_comments and (not isinstance(node, JsxElement) or not self.jsx_transform):
Thanks, done

2024-05-12 23:57 UTC, davecoates commented on packages/ap-codegen/alliance_platform/codegen/printer.py
> +        self.node_stack.append(node)
Good point, done

2024-05-13 01:02 UTC, micahklaz approved these changes
LGTM

2024-05-13 01:05 UTC, merged